binser_instrument_shop_index:
    path:     /
    defaults: { _controller: BinserInstrumentBundle:Shop/View:index }

binser_instrument_shop_product:
    path:     /product/{productId}
    defaults: { _controller: BinserInstrumentBundle:Shop/View:product }

binser_instrument_shop_search:
    path:     /search/{searchString}
    defaults: { _controller: BinserInstrumentBundle:Shop/View:searchProducts }

binser_instrument_shop_category:
    path:     /{categoryUrl}
    defaults: { _controller: BinserInstrumentBundle:Shop/View:categoryProducts }

binser_instrument_shop_subcategory:
    path:     /{categoryUrl}/{subcategoryUrl}
    defaults: { _controller: BinserInstrumentBundle:Shop/View:subcategoryProducts }
