<?php

namespace Binser\InstrumentBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserComments($user)
    {
        return $this->findBy(array('author' => $user));
    }
}
