<?php

namespace Binser\InstrumentBundle\Repository;
use Binser\InstrumentBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Post[]
     */
    public function getEnabledPosts()
    {
        return $this->findBy(array('enabled' => true));
    }
}
