<?php

namespace Binser\InstrumentBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProductsByString($searchStrings)
    {
        $qb = $this->createQueryBuilder('p');
        return $qb->where($qb->expr()->like('LOWER(p.title)', '?1'))
            ->setParameter('1', '%' . mb_strtolower($searchStrings, 'UTF-8') . '%')
            ->getQuery()
            ->getResult();
    }
}
