<?php

namespace Binser\InstrumentBundle\Repository;
use Binser\InstrumentBundle\Entity\Service;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $url
     * @return Service|null
     */
    public function getPostByUrl($url)
    {
        return $this->findOneBy(['url' => $url]);
    }

    /**
     * @return Service[]
     */
    public function getEnabledServices()
    {
        return $this->findOneBy(['enabled' => true]);
    }
}
