<?php

namespace Binser\InstrumentBundle\Repository;
use Binser\InstrumentBundle\Entity\SubCategory;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $category
     * @param $url
     * @return SubCategory|null
     */
    public function getCategoryByCategoryAndUrl($category, $url)
    {
        return $this->findOneBy(['category' => $category, 'url' => $url]);
    }
}
