binser_instrument_homepage:
    path:     /
    defaults: { _controller: BinserInstrumentBundle:View:index }

binser_instrument_blog:
    path:     /blog
    defaults: { _controller: BinserInstrumentBundle:View:blog }

binser_instrument_blog_post:
    path:     /blog/{link}
    defaults: { _controller: BinserInstrumentBundle:View:blogPost }

binser_instrument_shop_index:
    path:     /shop
    defaults: { _controller: BinserInstrumentBundle:Shop/View:index }
