binser_instrument_homepage:
    path:     /
    defaults: { _controller: BinserInstrumentBundle:View:index }

binser_instrument_blog:
    path:     /blog
    defaults: { _controller: BinserInstrumentBundle:View:blog }

binser_instrument_blog_post:
    path:     /blog/{link}
    defaults: { _controller: BinserInstrumentBundle:View:blogPost }

binser_instrument_shop_index:
    path:     /shop
    defaults: { _controller: BinserInstrumentBundle:Shop/View:index }

binser_instrument_shop_product:
    path:     /shop/product/{productId}
    defaults: { _controller: BinserInstrumentBundle:Shop/View:product }

binser_instrument_shop_search:
    path:     /shop/search/{searchString}
    defaults: { _controller: BinserInstrumentBundle:Shop/View:searchProducts }

binser_instrument_shop_category:
    path:     /shop/{categoryUrl}
    defaults: { _controller: BinserInstrumentBundle:Shop/View:categoryProducts }

binser_instrument_shop_subcategory:
    path:     /shop/{categoryUrl}/{subcategoryUrl}
    defaults: { _controller: BinserInstrumentBundle:Shop/View:subcategoryProducts }
