services:
  app.menu_builder:
    class: Binser\InstrumentBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory", @doctrine.orm.entity_manager]

  app.main_menu:
    class: Knp\Menu\MenuItem
    factory: ["@app.menu_builder", createMainMenu]
    tags:
      - { name: knp_menu.menu, alias: main }

  app.shop_menu:
    class: Knp\Menu\MenuItem
    factory: ["@app.menu_builder", createShopMenu]
    tags:
      - { name: knp_menu.menu, alias: shop }

  admin.post:
    class: Binser\InstrumentBundle\Admin\PostAdmin
    arguments: [~, Binser\InstrumentBundle\Entity\Post, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Статейник, label: Посты }

  admin.service:
    class: Binser\InstrumentBundle\Admin\ServiceAdmin
    arguments: [~, Binser\InstrumentBundle\Entity\Service, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Услуги, label: Услуги }

  admin.category:
    class: Binser\InstrumentBundle\Admin\CategoryAdmin
    arguments: [~, Binser\InstrumentBundle\Entity\Category, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Интернет магазин, label: Категории }

  admin.subcategory:
    class: Binser\InstrumentBundle\Admin\SubCategoryAdmin
    arguments: [~, Binser\InstrumentBundle\Entity\SubCategory, ~]
    tags:
      - { name: sonata.admin, manager_type: orm,  group: Интернет магазин, label: Подкатегории }

  admin.product:
    class: Binser\InstrumentBundle\Admin\ProductAdmin
    arguments: [~, Binser\InstrumentBundle\Entity\Product, ~]
    tags:
      - { name: sonata.admin, manager_type: orm,  group: Интернет магазин, label: Продукты }


  shop.form.order:
      class: Binser\InstrumentBundle\Form\OrderType
      arguments: [@session, @security.context]
      tags:
          - { name: form.type, alias: shop_order }

  shop.backet.extention:
        class: Binser\InstrumentBundle\Twig\Extension\BasketExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
